# Generated by Django 3.2 on 2021-05-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='titledesc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
